/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwipeRouteImport } from './routes/swipe'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MapRouteImport } from './routes/map'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as ApiTrackVisitRouteImport } from './routes/api.track-visit'
import { Route as ApiTrackActivityRouteImport } from './routes/api.track-activity'

const SwipeRoute = SwipeRouteImport.update({
  id: '/swipe',
  path: '/swipe',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackVisitRoute = ApiTrackVisitRouteImport.update({
  id: '/api/track-visit',
  path: '/api/track-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackActivityRoute = ApiTrackActivityRouteImport.update({
  id: '/api/track-activity',
  path: '/api/track-activity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/swipe': typeof SwipeRoute
  '/api/track-activity': typeof ApiTrackActivityRoute
  '/api/track-visit': typeof ApiTrackVisitRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/swipe': typeof SwipeRoute
  '/api/track-activity': typeof ApiTrackActivityRoute
  '/api/track-visit': typeof ApiTrackVisitRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/swipe': typeof SwipeRoute
  '/api/track-activity': typeof ApiTrackActivityRoute
  '/api/track-visit': typeof ApiTrackVisitRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/insights'
    | '/map'
    | '/onboarding'
    | '/swipe'
    | '/api/track-activity'
    | '/api/track-visit'
    | '/listings/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/insights'
    | '/map'
    | '/onboarding'
    | '/swipe'
    | '/api/track-activity'
    | '/api/track-visit'
    | '/listings/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/insights'
    | '/map'
    | '/onboarding'
    | '/swipe'
    | '/api/track-activity'
    | '/api/track-visit'
    | '/listings/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  InsightsRoute: typeof InsightsRoute
  MapRoute: typeof MapRoute
  OnboardingRoute: typeof OnboardingRoute
  SwipeRoute: typeof SwipeRoute
  ApiTrackActivityRoute: typeof ApiTrackActivityRoute
  ApiTrackVisitRoute: typeof ApiTrackVisitRoute
  ListingsIdRoute: typeof ListingsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swipe': {
      id: '/swipe'
      path: '/swipe'
      fullPath: '/swipe'
      preLoaderRoute: typeof SwipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-visit': {
      id: '/api/track-visit'
      path: '/api/track-visit'
      fullPath: '/api/track-visit'
      preLoaderRoute: typeof ApiTrackVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-activity': {
      id: '/api/track-activity'
      path: '/api/track-activity'
      fullPath: '/api/track-activity'
      preLoaderRoute: typeof ApiTrackActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  InsightsRoute: InsightsRoute,
  MapRoute: MapRoute,
  OnboardingRoute: OnboardingRoute,
  SwipeRoute: SwipeRoute,
  ApiTrackActivityRoute: ApiTrackActivityRoute,
  ApiTrackVisitRoute: ApiTrackVisitRoute,
  ListingsIdRoute: ListingsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
